### ISSUE TITLE
Waiting for reply does not send heartbeat, so Combob device may potentially reset

### ISSUE THREAD

**Issue by rmick** [rmick/Combobulator#2]
User have reported the Combobulator device resetting in rehost mode.

Need to check if a heartbeat is needed, or if the HostGame window Is still transmitting game time signals.

**Comment by mikeage** [comment]
I'm not sure what ReHost mode is, but I see quite a few restarts while players are joining; it seems to all work out eventually, but it wastes a lot of time while the device resets, and my tablet has to reconnect. Are there any logs I can get you to help with this?

**Comment by rmick** [comment]
I think I found this yesterday.
The software stops sending host commands when it gets a reply from a tagger. It has a timeout of 5 seconds, but does not send a heartbeat during this time, hence the reset. 
I will do a new build today.

**Comment by rmick** [comment]
> Fixed b18.12..03
> 
Waiting for reply did not send heartbeat. This loop resets out after 5 tries (total time = 6x850mS) but the hardware times out after 5sec.
