### ISSUE TITLE
Low battery shown when actual battery level is ~4.8/4.9V

### ISSUE THREAD

**Issue by mikeage** [rmick/Combobulator#4]
I've received low battery warnings when the combobulator's screen shows a voltage of 4.8 or 4.9V. It might just be a momentary drop, but the batteries shouldn't really be doing that (eneloops, at least 70% charged)

**Comment by rmick** [comment]
Fixed in v1.021

**Comment by mikeage** [comment]
thanks. Is dropbox updated? I see v1.02 there, and I currently have "v1.01 - r18.11.01"

[not that urgent for me personally, as I found that it was pretty straightforward to build for Mac at least, even without installing QtCreator or anything]

**Comment by rmick** [comment]
Closed
